/* eslint-disable react/no-unescaped-entities */
import React from "react";

export const TermsEn = () => (
  <>
    <p>
      <span>**Security of the Website**</span>
      <br />
      <br />
      Welcome to the website: "Granite and Gravel Quarry of Soroca"! The website{" "}
      <a href="https://www.cariera-cosauti.md">www.cariera-cosauti.md</a> is
      owned and managed by JSC "Cariera de granit şi pietriş din Soroca",
      located in Soroca city, 4 Cosăuți Street, with the following contact
      details: email: info@cariera-cosauti.md, tel: +373 230 20710, hereinafter
      referred to as the company.
      <br />
      <br />
      The company pays special attention to protecting the confidentiality and
      personal data of its users. We have developed this website security policy
      to inform you about the type of personal information we collect, how we
      use it, our measures to protect it, and who has access to the collected
      data. We are committed to updating and correcting discrepancies in the
      information taken. The company reserves the right to update this policy by
      modifying the version and date, and we recommend checking periodically for
      any updates. By accessing our site, you agree to the terms outlined in
      this website security policy and the use of cookies as described below.
      <br />
      <br />
      **Information Collection**
      <br />
      When using our website, it's important to know that we collect and store
      various types of personal data related to you, such as your name and email
      address, when accessing the site. It should be mentioned that by visiting
      a website, you disclose certain information, such as your IP address,
      visit time, location on our site, type of browser, and operating system
      used. The web pages you access may also record this information. If you
      access our site from a mobile device or similar, we may collect the unique
      identification number of that device. This data helps us tailor content
      and services to the device used.
      <br />
      <br />
      **Website Visitors**
      <br />
      To improve the functionality and user-friendliness of our website, we
      collect anonymous information about the pages accessed and how you
      navigate the site. This information is used to monitor traffic and
      optimize the experience for our visitors.
      <br />
      <br />
      **Contact**
      <br />
      If you access the "Contact" section of the site and fill in the requested
      information under the "Personal" section, we will use your information to
      manage your inquiries and respond to you. Please note that there is the
      possibility of storing the information provided by you for future
      reference and to continually assess how well we provide this service to
      both you and others. If you write to us, call us, or send us emails, we
      will use your details to respond, keeping a record of your correspondence
      with us.
      <br />
      <br />
      **Information Sharing**
      <br />
      We will not transmit your information to third parties without your
      consent, except as required by law or a public authority.
      <br />
      <br />
      **Security**
      <br />
      We are committed to maintaining the security and confidentiality of your
      information and will use appropriate technical and organizational security
      measures to prevent loss or unauthorized access.
      <br />
      <br />
      The password for the{" "}
      <a href="https://www.cariera-cosauti.md">www.cariera-cosauti.md</a> portal
      is known only to the client (and designated employees), and the client is
      responsible for maintaining the security of the password and assumes full
      responsibility in case of its disclosure to third parties, even in the
      case of accidental disclosure.
      <br />
      Measures the{" "}
      <a href="https://www.cariera-cosauti.md">www.cariera-cosauti.md</a> portal
      client must take include:
      <br />
    </p>
    <ul>
      <li>
        Not storing the password in visible places (e.g., written on paper).
      </li>
      <li>
        Not disclosing the password to employees other than those designated to
        work on the portal.
      </li>
      <li>
        Not providing the password in response to email or phone requests to
        avoid the risk of malicious attacks (phishing).
      </li>
    </ul>
    <br />
    <p>
      **Cookie Statement**
      <br />
      This site uses cookies. A cookie is a small data file generated by a
      website and saved by your web browser, collecting information about your
      online behavior. Its purpose is to remember information about you, similar
      to a preference file created by software. Cookies perform various
      functions. Cookies can be "persistent," remaining stored on your device
      after leaving the site, or "session" cookies, which are deleted after
      closing the internet browser. You can use your browser settings to manage
      cookie preferences, but doing so may result in some features of the site
      not being available or functioning at full capacity. The company will not
      personally identify visitors and will not use cookies to contact you,
      committing to respect your privacy at all times.
      <br />
      <br />
      **Website Content**
      <br />
      The company is committed to making maximum efforts regarding the
      information made available to visitors on its website,{" "}
      <a href="https://www.cariera-cosauti.md">www.cariera-cosauti.md</a>.
      Although all efforts have been made to ensure the correctness and
      reliability of the information contained on the website, the company
      cannot be held responsible for any errors, omissions, or outcomes
      resulting from the use of this information. The website{" "}
      <a href="https://www.cariera-cosauti.md">www.cariera-cosauti.md</a> is
      normally accessible 24/7. In situations beyond the company's control,
      difficulties associated with information systems, difficulties associated
      with telecommunications networks, other technical issues, or for
      maintenance—this list is not exhaustive—the company may decide to suspend
      or interrupt access, total or partial, to the site. The website may be
      modified without prior notice. Any reproduction or use, even partial, of
      any element of the{" "}
      <a href="https://www.cariera-cosauti.md">www.cariera-cosauti.md</a>{" "}
      website within another website through framing, integration, or any
      similar process is strictly prohibited, except for exceptional
      authorization from the company. To obtain authorization for the mentioned
      hyperlinks, please contact the company by email at
      info@cariera-cosauti.md. The request must include the URL where the
      hyperlinks are desired to be established. Access to the page containing
      hyperlinks to the{" "}
      <a href="https://www.cariera-cosauti.md">www.cariera-cosauti.md</a>{" "}
      website should be free.
      <br />
      <br />
      The site is subject to change without notice. Any reproduction or use,
      even partial, of any element of{" "}
      <a href="https://www.cariera-cosauti.md">www.cariera-cosauti.md</a> within
      another website by framing, integration or any other similar process is
      strictly prohibited, except with the exclusive authorization of the
      company.
      <br />
      To obtain permission to set the above hyperlinks, you must contact the
      company by e-mail: info@cariera-cosauti.md. The request must specify the
      URL to which the hyperlink is to be set.
      <br />
      Access to the page containing hyperlinks to{" "}
      <a href="https://www.cariera-cosauti.md">www.cariera-cosauti.md</a> must
      be free of charge. <br /> <br />
      Trademarks and copyrights
      <br />
      All rights, title and value belong to the Company. The use of the
      Company's name without its consent is prohibited. The contents of this
      website and the website itself are protected by intellectual property
      laws, in particular trademarks, copyrights, designs and models.
      <br />
      In accordance with intellectual property laws and international treaties
      and agreements governing copyright protection, it is prohibited to
      reproduce (except for personal use), commercialize, distribute, transmit,
      adapt, modify, publish, communicate all or part of the data, presentation
      or structure of the website, which are protected by copyright and
      published on{" "}
      <a href="https://www.cariera-cosauti.md">www.cariera-cosauti.md</a>,
      without the express and prior consent of the owner of the copyright
      relating to that presentation or structure.
      <br />
      It is also prohibited to enter data into{" "}
      <a href="https://www.cariera-cosauti.md">www.cariera-cosauti.md</a> in any
      way that may change the content or publication of data, presentation or
      structure of the website presented on the company's website.
      <br />
      <br />
      For more information, contact the following address:
      info@cariera-cosauti.md. Copyright © {new Date().getFullYear()}. All
      rights reserved.
    </p>
  </>
);
